const definitions = [
  {name: 'request', wrapper: 'promisify', group: 'net'},
  {name: 'uploadFile', wrapper: 'promisify', group: 'file'},
  {name: 'downloadFile', wrapper: 'promisify', group: 'file'},
  {name: 'connectSocket', wrapper: 'promisify', group: 'net'},
  {name: 'onSocketOpen', wrapper: 'delegate', group: 'net'},
  {name: 'onSocketError', wrapper: 'delegate', group: 'net'},
  {name: 'sendSocketMessage', wrapper: 'promisify', group: 'net'},
  {name: 'onSocketMessage', wrapper: 'delegate', group: 'net'},
  {name: 'closeSocket', wrapper: 'delegate', group: 'net'},
  {name: 'onSocketClose', wrapper: 'delegate', group: 'net'},
  {name: 'chooseImage', wrapper: 'promisify', group: 'media'},
  {name: 'previewImage', wrapper: 'promisify', group: 'media'},
  {name: 'getImageInfo', wrapper: 'promisify', group: 'media'},
  {name: 'startRecord', wrapper: 'promisify', group: 'media'},
  {name: 'stopRecord', wrapper: 'delegate', group: 'media'},
  {name: 'playVoice', wrapper: 'promisify', group: 'media'},
  {name: 'pauseVoice', wrapper: 'delegate', group: 'media'},
  {name: 'stopVoice', wrapper: 'delegate', group: 'media'},
  {name: 'getBackgroundAudioPlayerState', wrapper: 'promisify', group: 'media'},
  {name: 'playBackgroundAudio', wrapper: 'promisify', group: 'media'},
  {name: 'pauseBackgroundAudio', wrapper: 'delegate', group: 'media'},
  {name: 'seekBackgroundAudio', wrapper: 'promisify', group: 'media'},
  {name: 'stopBackgroundAudio', wrapper: 'delegate', group: 'media'},
  {name: 'onBackgroundAudioPlay', wrapper: 'delegate', group: 'media'},
  {name: 'onBackgroundAudioPause', wrapper: 'delegate', group: 'media'},
  {name: 'onBackgroundAudioStop', wrapper: 'delegate', group: 'media'},
  {name: 'createAudioContext', wrapper: 'delegate', group: 'media'},
  {name: 'chooseVideo', wrapper: 'promisify', group: 'media'},
  {name: 'createVideoContext', wrapper: 'delegate', group: 'media'},
  {name: 'saveFile', wrapper: 'promisify', group: 'file'},
  {name: 'getSavedFileList', wrapper: 'promisify', group: 'file'},
  {name: 'getSavedFileInfo', wrapper: 'promisify', group: 'file'},
  {name: 'removeSavedFile', wrapper: 'promisify', group: 'file'},
  {name: 'openDocument', wrapper: 'promisify', group: 'file'},
  {name: 'setStorage', wrapper: 'promisify', group: 'storage'},
  {name: 'getStorage', wrapper: 'promisify', group: 'storage'},
  {name: 'getStorageInfo', wrapper: 'promisify', group: 'storage'},
  {name: 'removeStorage', wrapper: 'promisify', group: 'storage'},
  {name: 'clearStorage', wrapper: 'promisify', group: 'storage'},
  {name: 'setStorageSync', wrapper: 'delegate', group: 'storage'},
  {name: 'getStorageSync', wrapper: 'delegate', group: 'storage'},
  {name: 'getStorageInfoSync', wrapper: 'delegate', group: 'storage'},
  {name: 'removeStorageSync', wrapper: 'delegate', group: 'storage'},
  {name: 'clearStorageSync', wrapper: 'delegate', group: 'storage'},
  {name: 'getLocation', wrapper: 'promisify', group: 'geo'},
  {name: 'chooseLocation', wrapper: 'promisify', group: 'geo'},
  {name: 'openLocation', wrapper: 'promisify', group: 'geo'},
  {name: 'createMapContext', wrapper: 'delegate', group: 'geo'},
  {name: 'getSystemInfo', wrapper: 'promisify', group: 'device'},
  {name: 'getSystemInfoSync', wrapper: 'delegate', group: 'device'},
  {name: 'getNetworkType', wrapper: 'promisify', group: 'device'},
  {name: 'onAccelerometerChange', wrapper: 'delegate', group: 'device'},
  {name: 'onCompassChange', wrapper: 'delegate', group: 'device'},
  {name: 'makePhoneCall', wrapper: 'promisify', group: 'device'},
  {name: 'scanCode', wrapper: 'promisify', group: 'device'},
  {name: 'showToast', wrapper: 'promisify', group: 'ui'},
  {name: 'hideToast', wrapper: 'delegate', group: 'ui'},
  {name: 'showModal', wrapper: 'promisify', group: 'ui'},
  {name: 'showActionSheet', wrapper: 'promisify', group: 'ui'},
  {name: 'setNavigationBarTitle', wrapper: 'promisify', group: 'ui'},
  {name: 'showNavigationBarLoading', wrapper: 'delegate', group: 'ui'},
  {name: 'hideNavigationBarLoading', wrapper: 'delegate', group: 'ui'},
  {name: 'navigateTo', wrapper: 'promisify', group: 'ui'},
  {name: 'redirectTo', wrapper: 'promisify', group: 'ui'},
  {name: 'switchTab', wrapper: 'promisify', group: 'ui'},
  {name: 'navigateBack', wrapper: 'delegate', group: 'ui'},
  {name: 'createAnimation', wrapper: 'delegate', group: 'ui'},
  {name: 'createCanvasContext', wrapper: 'delegate', group: 'ui'},
  {name: 'createContext', wrapper: 'delegate', group: 'ui'},
  {name: 'drawCanvas', wrapper: 'delegate', group: 'ui'},
  {name: 'canvasToTempFilePath', wrapper: 'delegate', group: 'ui'},
  {name: 'stopPullDownRefresh', wrapper: 'delegate', group: 'ui'},
  {name: 'login', wrapper: 'promisify', group: 'auth'},
  {name: 'checkSession', wrapper: 'promisify', group: 'auth'},
  {name: 'getUserInfo', wrapper: 'promisify', group: 'auth'},
  {name: 'requestPayment', wrapper: 'promisify', group: 'payment'}
]

export default function(grouped){
  if(grouped){
    return definitions.reduce((mem, {group, ...props}) => {
      mem[group] = mem[group] || []
      mem[group].push({...props})
      return mem
    }, {})
  }
  return definitions.map(({name, wrapper}) => ({name, wrapper}))
}
