require('core-js/fn/number/is-finite')
require('core-js/fn/number/is-nan')
require('core-js/fn/number/is-integer')
require('core-js/fn/number/is-safe-integer')
// require('core-js/fn/number/parse-float')
// require('core-js/fn/number/parse-int')
require('core-js/fn/number/epsilon')
require('core-js/fn/number/max-safe-integer')
require('core-js/fn/number/min-safe-integer')
require('core-js/fn/number/to-fixed')
require('core-js/fn/number/to-precision')
